# Generated by Django 3.2.12 on 2022-05-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(help_text='Выберите изображение', null=True, upload_to='uploads/users_images', verbose_name='Изображение пользователя'),
        ),
    ]
