# Generated by Django 3.2.12 on 2022-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(help_text='Выберите изображение группы', null=True, upload_to='uploads/groups_images', verbose_name='Изображение группы'),
        ),
    ]
