# Generated by Django 3.2.12 on 2022-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='None', help_text='Используйте буквы, цифры или @/./+/-/_ ', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
