# Generated by Django 3.2.12 on 2022-05-03 19:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_channels', '0002_alter_userschannel_slug'),
        ('users_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMessagesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата создания')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_containers', to='users_channels.userschannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Контейнер сообщений канала',
                'verbose_name_plural': 'Контейнеры сообщений канала',
            },
        ),
        migrations.CreateModel(
            name='DailyMessagesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата создания')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_containers', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Контейнер сообщений группы',
                'verbose_name_plural': 'Контейнеры сообщений группы',
            },
        ),
        migrations.CreateModel(
            name='UserChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст')),
                ('time', models.TimeField(default=datetime.datetime(2022, 5, 3, 23, 38, 28, 110076), null=True, verbose_name='Время отправки')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_messages', to='users_messages.dailymessageschannel', verbose_name='Контейнер')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение канала',
                'verbose_name_plural': 'Сообщения канала',
            },
        ),
        migrations.CreateModel(
            name='UserGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст')),
                ('time', models.TimeField(default=datetime.datetime(2022, 5, 3, 23, 38, 28, 110076), null=True, verbose_name='Время отправки')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to='users_messages.dailymessagesgroup', verbose_name='Контейнер')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение группы',
                'verbose_name_plural': 'Сообщения группы',
            },
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
