# Generated by Django 3.2.12 on 2022-05-04 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0002_auto_20220503_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 4, 21, 36, 16, 997528), null=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='usergroupmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 4, 21, 36, 16, 997528), null=True, verbose_name='Время отправки'),
        ),
    ]
