# Generated by Django 3.2.12 on 2022-05-04 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0003_auto_20220504_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 4, 22, 56, 28, 527462), null=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='usergroupmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 4, 22, 56, 28, 527462), null=True, verbose_name='Время отправки'),
        ),
    ]
