# Generated by Django 3.2.12 on 2022-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0004_auto_20220503_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannelmessage',
            name='daterime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergroupmessage',
            name='daterime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
