# Generated by Django 3.2.12 on 2022-05-05 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_image'),
        ('users_channels', '0002_alter_userschannel_slug'),
        ('users_messages', '0004_auto_20220504_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyMessagesChannel',
            new_name='DailyChannelMessages',
        ),
        migrations.RenameModel(
            old_name='DailyMessagesGroup',
            new_name='DailyGroupMessages',
        ),
        migrations.AlterField(
            model_name='userchannelmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 5, 18, 48, 21, 560786), null=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='usergroupmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 5, 18, 48, 21, 560786), null=True, verbose_name='Время отправки'),
        ),
    ]
