# Generated by Django 3.2.12 on 2022-05-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0005_auto_20220503_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchannelmessage',
            name='daterime',
        ),
        migrations.RemoveField(
            model_name='usergroupmessage',
            name='daterime',
        ),
    ]
