# Generated by Django 3.2.12 on 2022-05-08 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0006_auto_20220505_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelmessage',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usergroupmessage',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
    ]
