# Generated by Django 3.2.12 on 2022-05-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0006_auto_20220505_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelmessage',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='usergroupmessage',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время отправки'),
        ),
    ]
