# Generated by Django 3.2.12 on 2022-05-03 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_messages', '0006_auto_20220503_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannelmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 3, 21, 57, 36, 532279), null=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='usergroupmessage',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 3, 21, 57, 36, 532279), null=True, verbose_name='Время отправки'),
        ),
    ]
