# Generated by Django 3.2.12 on 2022-05-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('users_messages', '0009_rename_chatmessage_userchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychatmessages',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_containers', to='chats.chat', verbose_name='Чат'),
        ),
    ]
