# Generated by Django 3.2.12 on 2022-05-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default group name', help_text='Введите название, длина до 150 символов', max_length=150, verbose_name='Название')),
                ('image', models.ImageField(help_text='Выберите изображение группы', null=True, upload_to='uploads/', verbose_name='Изображение группы')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
