# Generated by Django 3.2.12 on 2022-05-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userschannel',
            options={},
        ),
    ]
