# Generated by Django 3.2.12 on 2022-05-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_channels', '0002_alter_userschannel_image'),
        ('users_channels', '0002_alter_userschannel_options'),
    ]

    operations = [
    ]
