# Generated by Django 3.2.12 on 2022-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_channels', '0003_merge_20220503_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userschannel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.RemoveField(
            model_name='userschannel',
            name='id',
        ),
        migrations.AddField(
            model_name='userschannel',
            name='slug',
            field=models.SlugField(default='None', help_text='Используйте буквы, цифры или @/./+/-/_ ', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='userschannel',
            name='image',
            field=models.ImageField(help_text='Выберите изображение канала', null=True, upload_to='uploads/groups_images', verbose_name='Изображение канала'),
        ),
    ]
